import { styled } from "@kuma-ui/core";
import { Inter } from "next/font/google";

import type { Metadata } from "next";

import "@acab/reset.css";
import "@/app/theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Html lang="ja">
			<Body className={inter.className}>{children}</Body>
		</Html>
	);
}

const Html = styled.html`
	background: var(--background);
	height: 100%;

	h1 {
		font-size: 1.2rem;

		@media (min-width: t("breakpoints.screen2")) {
			font-size: 1.5rem;
		}
	}

	h2 {
		font-size: 1.1rem;

		@media (min-width: t("breakpoints.screen2")) {
			font-size: 1.25rem;
		}
	}
`;

const Body = styled.body`
	height: 100%;
`;
