import { styled } from "@kuma-ui/core";
import { Inter } from "next/font/google";

import type { Metadata } from "next";

import "@acab/reset.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Html lang="ja">
			<Body className={inter.className}>{children}</Body>
		</Html>
	);
}

const Html = styled.html`
	--background-primary: #f0f0f0;
	--background-secondary: #ffffff;

	--text-primary: #000000;
	--text-secondary: #666666;

	background: var(--background-primary);
	height: 100%;
`;
const Body = styled.body`
	height: 100%;
`;
